#!/bin/sh

# shellcheck disable=SC1090
. "$(dirname "$0")/alltags.sh"

IMG=$(dirname "$DOCKER_REPO")/alpine
for tag in $(alltags "$IMG"); do
    if [ -n "$tag" ]; then
        echo "============== Building ${DOCKER_REPO}:$tag"
        docker push ${DOCKER_REPO}:$tag
    fi
done